## DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/codigomariano_game
spring.datasource.username=codigo_usr
spring.datasource.password=OneCodigo3347
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
